FROM registry.astralinux.ru/library/astra/ubi18:latest

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential cmake git ca-certificates libpq-dev \
    postgresql-client gdb valgrind vim \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp
RUN git clone --branch 7.7.5 https://github.com/jtv/libpqxx.git && \
    cd libpqxx && mkdir build && cd build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=20 && \
    make -j$(nproc) && make install && \
    rm -rf /tmp/libpqxx

WORKDIR /app
COPY . /app

RUN mkdir /tmp/build && cd /tmp/build && \
    cmake /app -DCMAKE_PREFIX_PATH=/usr/local -DCMAKE_BUILD_TYPE=Release && \
    make -j$(nproc) && \
    cp /tmp/build/TagsWriter /usr/local/bin/TagsWriter && \
    rm -rf /tmp/build

CMD ["/bin/bash"]