FROM registry.astralinux.ru/library/astra/ubi18:latest

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    cmake \
    git \
    ca-certificates \
    libpq-dev \
    postgresql-client \
    && rm -rf /var/lib/apt/lists/*

# libpqxx
WORKDIR /tmp
RUN git clone --branch 7.7.5 https://github.com/jtv/libpqxx.git && \
    cd libpqxx && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=Release && \
    make -j$(nproc) && make install && \
    rm -rf /tmp/libpqxx

WORKDIR /app

RUN mkdir build

CMD ["/bin/bash"]